version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./Experiment:/app/Experiment
    environment:
      - FLASK_APP=server.py
      - FLASK_ENV=production
    restart: always